
package competicao2;
import java.util.Scanner;
public class Competicao2 {
    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);
        int cont=1;
        System.out.println("0");
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        cont = cont+1;
        System.out.println(cont);
        
        
    }
    
}
